### ISSUE TITLE
How to reload images data in CollectionView in good performance?

### ISSUE THREAD

**Issue by gztchan** [ashfurrow/AFTabledCollectionView#12]
i put 9 images in the collectionView, and when i scroll the tableView, i found bad performance.

i am using
1. GCD to read cached images
2. image has been scaled down, so each image's resolution in collectionView is ScreenWidth / 3.f * SreenWidth / 3.f

so, can you give me some advices to improve the performance?

**Comment by vnchopra** [comment]
I have gone through this kind of problem before. You need to look at your instruments panel and notice memory allocation of images. De-allocate images when reusing cells.

**Comment by ashfurrow** [comment]
It's a really broad topic. Libraries like [SDWebImage](https://github.com/rs/SDWebImage) are a big help. Any tutorials you can find for UITableView work very well for collection views, too.
