### ISSUE TITLE
Decelerating

### ISSUE THREAD

**Issue by kubatru** [ashfurrow/AFTabledCollectionView#15]
If the collectionView is decelerating and you scroll the base tableView (e.g down), different rows are decelerating as well (same with your example)

**Comment by ashfurrow** [comment]
Good catch, there was a [similar issue](https://github.com/ashfurrow/Collection-View-in-a-Table-View-Cell/issues/7) reported on the Swift version of this repository, it has a corresponding fix. Let me know if I can clarify anything!

**Comment by kubatru** [comment]
This seems to be working.

**Comment by ashfurrow** [comment]
Awesome! Could I persuade you to open a pull request to fix the code in this repository?

**Comment by kubatru** [comment]
Yes, I also fixed the wrong `indexedCollectionView` implementation 
#16
