### ISSUE TITLE
Problem about two or more collection view in a cell

### ISSUE THREAD

**Issue by dwjdwj1216** [ashfurrow/AFTabledCollectionView#18]
I add two collection view in a cell. And I give this two different tag. What I doing in the delegate is to recognise the tag of the collection view to do different thing. I think it may work. But it doesn't. I set 2 item for first collection, and 5 for second. Actually the two collection view just to display the same number of items.Is there some problem about what i do?

**Comment by dwjdwj1216** [comment]
Omg, I find what the stupid thing I do. I didn't give the two collection view different layout!!! I think my lack knowledge about collection view cause this. I think this issue may help other persons.

**Comment by ashfurrow** [comment]
Glad you got it figured out! Don't worry, collection views as pretty tricky, everyone takes time to get proficient with them.
