### ISSUE TITLE
Can i use xib to build two or more collection?

### ISSUE THREAD

**Issue by dwjdwj1216** [ashfurrow/AFTabledCollectionView#19]
When I use xib to build, xcode didn't buy it. It says [AFIndexedCollectionView retain]: message sent to deallocated instance. What's the matter?

**Comment by dwjdwj1216** [comment]
And the tableview controller called -(NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView and -(NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section just no -(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath. Is it a bug when i use two collection view in one cell?How to fix it?

**Comment by dwjdwj1216** [comment]
OMG, damn layout!! I just reuse layout!!!!

**Comment by ashfurrow** [comment]
Hey, sorry to hear you're having trouble. Did you get it sorted out?

**Comment by dwjdwj1216** [comment]
YES. First I set two layout for controller property in the controller.  It's made the problem I mentioned.  Then i put the layout definition to the cellForRowAtIndexPath to avoid the reuse of layout. And the problems all gone. I made a conclusion about collection's layout usage: where use, where define.
