### ISSUE TITLE
tvOS keep focused cell on the left

### ISSUE THREAD

**Issue by shadzik** [ashfurrow/AFTabledCollectionView#22]
Hey,

I'm trying to keep the focused UICollectionViewCell on the left, so I'm disabling scrolling on the UICollectionView and scroll myself like this:

`- (void)collectionView:(UICollectionView *)collectionView didUpdateFocusInContext:(UICollectionViewFocusUpdateContext *)context withAnimationCoordinator:(UIFocusAnimationCoordinator *)coordinator
{
    if (!context.nextFocusedIndexPath) {
        return;
    }
    collectionView.scrollEnabled = NO;
    [collectionView scrollToItemAtIndexPath:context.nextFocusedIndexPath atScrollPosition:UICollectionViewScrollPositionLeft animated:YES];
}
`

unfortunately what happens is that the UITableView also scrolls down, which is not what I want, as I'm only scrolling to the right.

Do you have an idea why this is happening? The indexPath for the next UICollectionViewCell is the same for each UITableViewCell, so indexPath 0-0  in UICollectionView is obviously present in each UITableViewCell (I'm guessing that's why the focus engine in tvOS gets a bit confused). But this effect works for example in the Netflix app.

I'll appreciate any help.

Thanks!

**Comment by ashfurrow** [comment]
Hi there, I'm not sure – I've never done tvOS development. Could be some sort of focus-stealing behaviour, like when you scroll the collection the containing scroll view knows to change? Not sure. When you figure it out, will you let me know?

**Comment by shadzik** [comment]
Sure Ash, I'll try to figure it out today. When I do I'll definitely tell you here. But yes, I also think it's some kind of weird focus stealing behaviour. Let's see, maybe one must disable the scroll on the tableView and detect a horizontal swipe to do that...

**Comment by shadzik** [comment]
Ok, I've figured it out. The trick was to *not* disable scrolling on the collectionView and add apropriate index calculation in `tableView:didEndDisplayingCell:forRowAtIndexPath:` - that part was missing in my implementation - now, just using `[collectionView scrollToItemAtIndexPath:context.nextFocusedIndexPath atScrollPosition:UICollectionViewScrollPositionLeft animated:YES];
` gives you basically the same effect like the Netflix app has on Apple TV.

**Comment by ashfurrow** [comment]
Awesome! I'm glad you got it figured out 👍
