### ISSUE TITLE
Different CollectionView Cell Type

### ISSUE THREAD

**Issue by varunchopraWB** [ashfurrow/AFTabledCollectionView#5]
Hello AshFurrow,

I have looked at your tutorial and code and have implemented it as well, but i was wondering, what happens if i have to display a different collectionview cell with different dimensions on a different row in the uitableview?

Kind Regards,

Varun

**Comment by ashfurrow** [comment]
Shouldn't be hard – just customize the collection view that you add on that row. I can answer any specific questions about how you'd do that.

**Comment by varunchopraWB** [comment]
Thank you for that, i will try to attempt it. In the meantime, i am curious as to how did you manage the datasource for each individual collection view that lives in each individual uitableview row? I am really tempted to placed the collectionview datasource and delegate into the uitableviewcell subclass.

I know my questions seems vague, it be nice to be given direction :) Thank you so much!

**Comment by ashfurrow** [comment]
That's a defensible option. I like to keep data sources out of any view classes to maintain stricter MVC.

**Comment by varunchopraWB** [comment]
Dude i bought your book! :D

**Comment by ashfurrow** [comment]
@varunchopraWB Awesome, thanks!

**Comment by ashfurrow** [comment]
Going to close this issue now – feel free to reopen or open a new issue if I can be of further help!
