### ISSUE TITLE
How to use a nib for collectionViewCell in this example?

### ISSUE THREAD

**Issue by houmie** [ashfurrow/AFTabledCollectionView#7]
This is indeed an amazing example.  I was trying to achieve this for days and without this clean project, it would have been hard to get there.

The only drawback is I don't see a way to register the ```collectionViewCell``` to the ```collectionView```. It seems I am forced to do it in code. I rather design this on the nib in xcode, which is much easier getting constraints done.

e.g. we need to register the nib with the ```collectionView```, but thats not possible here:

```
UINib *nib = [UINib nibWithNibName:CollectionViewCellIdentifier bundle:[NSBundle mainBundle]];
[??? collectionView registerNib:nib forCellWithReuseIdentifier:newsCellReuseIdentifier];
```

Is there a way after all and I am missing it?

**Comment by ashfurrow** [comment]
Hey there! Thank you for the kind words! There absolutely is a way to do this – I'm curious why your solution isn't working. What error are you getting? Replacing [this](https://github.com/ashfurrow/AFTabledCollectionView/blob/master/AFTabledCollectionView/AFTableViewCell.m#L26) line with the two you have there should work.

**Comment by houmie** [comment]
You are right. I had overlooked it. Your suggestion works. Thank you very much.
