### ISSUE TITLE
didSelectItemAtIndexPath

### ISSUE THREAD

**Issue by bablu-joshi** [ashfurrow/AFTabledCollectionView#9]
not getting section info.

can anyone help?

**Comment by ashfurrow** [comment]
Hi! Happy to help. Could you describe the problem in more detail? What did you do, and what did you expect? What happened instead?

**Comment by bablu-joshi** [comment]
I want to move to next detail screen on click of a cell.
I am getting item but not the section in indexpath.

**Comment by ashfurrow** [comment]
Not really sure I follow. You mean that you want to respond to tapping on a collection view cell? What code have you written to try it?

**Comment by bablu-joshi** [comment]
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath{
    
    NSLog(@"item %li",indexPath.item);
    NSLog(@"item %li",indexPath.item);
    
    
}

**Comment by ashfurrow** [comment]
Right, so that's not a lot of information. From what I can gather, it looks like you want to do know table view cell a collection view cell is in when its tapped. This can be accomplished with this code:

```objc
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath{   
    NSIndexPath *tableViewIndexPath = [(AFIndexedCollectionView *)collectionView indexPath];
    NSLog(@"item %li", tableViewIndexPath.row);
    NSLog(@"item %li", tableViewIndexPath.section);
}
```

**Comment by bablu-joshi** [comment]
Great !! .thanks for the help..
